# Definitions for the hook user used to wait for CRDs to be established before deploying the rest of the application.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bootstrap-app-crd-waiter
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bootstrap-app-crd-waiter-role
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bootstrap-app-crd-waiter-binding
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
subjects:
  - kind: ServiceAccount
    name: bootstrap-app-crd-waiter
roleRef:
  kind: Role
  name: bootstrap-app-crd-waiter-role
  apiGroup: rbac.authorization.k8s.io
